// 小文字のマッピング
export const SMALL_KANA_MAP: { [key: string]: string[] } = {
  ぁ: ["la", "xa"],
  ぃ: ["li", "xi"],
  ぅ: ["lu", "xu"],
  ぇ: ["le", "xe"],
  ぉ: ["lo", "xo"],
  ゃ: ["lya", "xya"],
  ゅ: ["lyu", "xyu"],
  ょ: ["lyo", "xyo"],
  っ: ["ltu", "xtu"],
};

// な行の文字
export const NA_GYOU = new Set(["な", "に", "ぬ", "ね", "の", "にゃ", "にゅ", "にょ"])

// 基本的な文字のマッピング
export const BASIC_KANA_TO_ROMAN: { [key: string]: string[] } = {
  あ: ["a"],
  い: ["i", "yi"],
  う: ["u", "wu"],
  え: ["e"],
  お: ["o"],
  か: ["ka", "ca"],
  き: ["ki"],
  く: ["ku", "cu", "qu"],
  け: ["ke"],
  こ: ["ko", "co"],
  さ: ["sa"],
  し: ["si", "shi", "ci"],
  す: ["su"],
  せ: ["se", "ce"],
  そ: ["so"],
  た: ["ta"],
  ち: ["ti", "chi"],
  つ: ["tu", "tsu"],
  て: ["te"],
  と: ["to"],
  な: ["na"],
  に: ["ni"],
  ぬ: ["nu"],
  ね: ["ne"],
  の: ["no"],
  は: ["ha"],
  ひ: ["hi"],
  ふ: ["fu", "hu"],
  へ: ["he"],
  ほ: ["ho"],
  ま: ["ma"],
  み: ["mi"],
  む: ["mu"],
  め: ["me"],
  も: ["mo"],
  や: ["ya"],
  ゆ: ["yu"],
  よ: ["yo"],
  ら: ["ra"],
  り: ["ri"],
  る: ["ru"],
  れ: ["re"],
  ろ: ["ro"],
  わ: ["wa"],
  を: ["wo"],
  ん: ["nn", "xn"],
  が: ["ga"],
  ぎ: ["gi"],
  ぐ: ["gu"],
  げ: ["ge"],
  ご: ["go"],
  ざ: ["za"],
  じ: ["ji", "zi"],
  ず: ["zu"],
  ぜ: ["ze"],
  ぞ: ["zo"],
  だ: ["da"],
  ぢ: ["di"],
  づ: ["du"],
  で: ["de"],
  ど: ["do"],
  ば: ["ba"],
  び: ["bi"],
  ぶ: ["bu"],
  べ: ["be"],
  ぼ: ["bo"],
  ぱ: ["pa"],
  ぴ: ["pi"],
  ぷ: ["pu"],
  ぺ: ["pe"],
  ぽ: ["po"],
  ー: ["-"],
  ",": [","],
  ".": ["."],
  "、": [","],
  "。": ["."],
  "・": ["/"],
  "？": ["?"],
  "！": ["!"],
  "１": ["1"],
  "２": ["2"],
  "３": ["3"],
  "４": ["4"],
  "５": ["5"],
  "６": ["6"],
  "７": ["7"],
  "８": ["8"],
  "９": ["9"],
};

// 複合文字の直接入力パターン
export const COMPOUND_KANA_TO_ROMAN: { [key: string]: string[] } = {
  うぁ: ["wha"],
  うぃ: ["whi"],
  うぇ: ["whe"],
  うぉ: ["who"],
  きゃ: ["kya"],
  きぃ: ["kyi"],
  きゅ: ["kyu"],
  きぇ: ["kye"],
  きょ: ["kyo"],
  くぁ: ["qa", "qwa"],
  くぃ: ["qi", "qwi"],
  くぇ: ["qe", "qwe"],
  くぉ: ["qo", "qwo"],
  しゃ: ["sya", "sha"],
  しぃ: ["syi"],
  しゅ: ["syu", "shu"],
  しぇ: ["sye", "she"],
  しょ: ["syo", "sho"],
  つぁ: ["tsa"],
  つぃ: ["tsi"],
  つぇ: ["tse"],
  つぉ: ["tso"],
  ちゃ: ["tya", "cha", "cya"],
  ちぃ: ["tyi"],
  ちゅ: ["tyu", "chu", "cyu"],
  ちぇ: ["tye", "che"],
  ちょ: ["tyo", "cho", "cyo"],
  てゃ: ["tha"],
  てぃ: ["thi"],
  てゅ: ["thu"],
  てぇ: ["the"],
  てょ: ["tho"],
  とぁ: ["twa"],
  とぃ: ["twi"],
  とぅ: ["twu"],
  とぇ: ["twe"],
  とぉ: ["two"],
  ひゃ: ["hya"],
  ひぃ: ["hyi"],
  ひゅ: ["hyu"],
  ひぇ: ["hye"],
  ひょ: ["hyo"],
  ふぁ: ["fa"],
  ふぃ: ["fi"],
  ふぇ: ["fe"],
  ふぉ: ["fo"],
  にゃ: ["nya"],
  にぃ: ["nyi"],
  にゅ: ["nyu"],
  にぇ: ["nye"],
  にょ: ["nyo"],
  みゃ: ["mya"],
  みぃ: ["myi"],
  みゅ: ["myu"],
  みぇ: ["mye"],
  みょ: ["myo"],
  りゃ: ["rya"],
  りぃ: ["ryi"],
  りゅ: ["ryu"],
  りぇ: ["rye"],
  りょ: ["ryo"],
  ヴぁ: ["va"],
  ヴぃ: ["vi"],
  ヴ: ["vu"],
  ヴぇ: ["ve"],
  ヴぉ: ["vo"],
  ぎゃ: ["gya"],
  ぎぃ: ["gyi"],
  ぎゅ: ["gyu"],
  ぎぇ: ["gye"],
  ぎょ: ["gyo"],
  ぐぁ: ["gwa"],
  ぐぃ: ["gwi"],
  ぐぅ: ["gwu"],
  ぐぇ: ["gwe"],
  ぐぉ: ["gwo"],
  じゃ: ["ja", "zya", "jya"],
  じぃ: ["jyi", "zyi"],
  じゅ: ["ju", "zyu", "jyu"],
  じぇ: ["je", "zye"],
  じょ: ["jo", "zyo", "jyo"],
  でゃ: ["dha"],
  でぃ: ["dhi"],
  でゅ: ["dhu"],
  でぇ: ["dhe"],
  でょ: ["dho"],
  ぢゃ: ["dya"],
  ぢぃ: ["dyi"],
  ぢゅ: ["dyu"],
  ぢぇ: ["dye"],
  ぢょ: ["dyo"],
  びゃ: ["bya"],
  びぃ: ["byi"],
  びゅ: ["byu"],
  びぇ: ["bye"],
  びょ: ["byo"],
  ぴゃ: ["pya"],
  ぴぃ: ["pyi"],
  ぴゅ: ["pyu"],
  ぴぇ: ["pye"],
  ぴょ: ["pyo"],
};

// 複合文字の分割パターンを生成
export const SPLIT_PATTERNS: { [key: string]: string[][] } = {
  きゃ: [
    ["ki", "lya"],
    ["ki", "xya"],
  ],
  きゅ: [
    ["ki", "lyu"],
    ["ki", "xyu"],
  ],
  きょ: [
    ["ki", "lyo"],
    ["ki", "xyo"],
  ],
  しゃ: [
    ["si", "lya"],
    ["si", "xya"],
    ["shi", "lya"],
    ["shi", "xya"],
  ],
  しゅ: [
    ["si", "lyu"],
    ["si", "xyu"],
    ["shi", "lyu"],
    ["shi", "xyu"],
  ],
  しょ: [
    ["si", "lyo"],
    ["si", "xyo"],
    ["shi", "lyo"],
    ["shi", "xyo"],
  ],
  ちゃ: [
    ["ti", "lya"],
    ["ti", "xya"],
    ["chi", "lya"],
    ["chi", "xya"],
  ],
  ちゅ: [
    ["ti", "lyu"],
    ["ti", "xyu"],
    ["chi", "lyu"],
    ["chi", "xyu"],
  ],
  ちょ: [
    ["ti", "lyo"],
    ["ti", "xyo"],
    ["chi", "lyo"],
    ["chi", "xyo"],
  ],
  にゃ: [
    ["ni", "lya"],
    ["ni", "xya"],
  ],
  にゅ: [
    ["ni", "lyu"],
    ["ni", "xyu"],
  ],
  にょ: [
    ["ni", "lyo"],
    ["ni", "xyo"],
  ],
  ひゃ: [
    ["hi", "lya"],
    ["hi", "xya"],
  ],
  ひゅ: [
    ["hi", "lyu"],
    ["hi", "xyu"],
  ],
  ひょ: [
    ["hi", "lyo"],
    ["hi", "xyo"],
  ],
  みゃ: [
    ["mi", "lya"],
    ["mi", "xya"],
  ],
  みゅ: [
    ["mi", "lyu"],
    ["mi", "xyu"],
  ],
  みょ: [
    ["mi", "lyo"],
    ["mi", "xyo"],
  ],
  りゃ: [
    ["ri", "lya"],
    ["ri", "xya"],
  ],
  りゅ: [
    ["ri", "lyu"],
    ["ri", "xyu"],
  ],
  りょ: [
    ["ri", "lyo"],
    ["ri", "xyo"],
  ],
  ぎゃ: [
    ["gi", "lya"],
    ["gi", "xya"],
  ],
  ぎゅ: [
    ["gi", "lyu"],
    ["gi", "xyu"],
  ],
  ぎょ: [
    ["gi", "lyo"],
    ["gi", "xyo"],
  ],
  じゃ: [
    ["ji", "lya"],
    ["ji", "xya"],
    ["zi", "lya"],
    ["zi", "xya"],
  ],
  じゅ: [
    ["ji", "lyu"],
    ["ji", "xyu"],
    ["zi", "lyu"],
    ["zi", "xyu"],
  ],
  じょ: [
    ["ji", "lyo"],
    ["ji", "xyo"],
    ["zi", "lyo"],
    ["zi", "xyo"],
  ],
  びゃ: [
    ["bi", "lya"],
    ["bi", "xya"],
  ],
  びゅ: [
    ["bi", "lyu"],
    ["bi", "xyu"],
  ],
  びょ: [
    ["bi", "lyo"],
    ["bi", "xyo"],
  ],
  ぴゃ: [
    ["pi", "lya"],
    ["pi", "xya"],
  ],
  ぴゅ: [
    ["pi", "lyu"],
    ["pi", "xyu"],
  ],
  ぴょ: [
    ["pi", "lyo"],
    ["pi", "xyo"],
  ],
};
