default: &default
  adapter: postgresql
  encoding: utf8
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password: password
  database: app_development
  host: db

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  # database: path/to/persistent/storage/production.sqlite3
